<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="processmodel" nsURI="metamodels.processmodel" nsPrefix="be.uantwerpen.msdl.metamodels">
  <eClassifiers xsi:type="ecore:EClass" name="ProcessModel" eSuperTypes="#//base/NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ftg" lowerBound="1" eType="#//ftg/FormalismTransformationGraph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" upperBound="-1"
        eType="#//pm/Process" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyModel" eType="#//properties/PropertyModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceModel" eType="#//resources/ResourceModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="costModel" eType="#//cost/CostModel"
        containment="true"/>
  </eClassifiers>
  <eSubpackages name="ftg" nsURI="metamodels.ftg" nsPrefix="be.uantwerpen.msdl.metamodels">
    <eClassifiers xsi:type="ecore:EClass" name="FormalismTransformationGraph">
      <eStructuralFeatures xsi:type="ecore:EReference" name="formalism" upperBound="-1"
          eType="#//ftg/Formalism" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transformation" upperBound="-1"
          eType="#//ftg/Transformation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Formalism" eSuperTypes="#//base/Identifiable #//ftg/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputOf" upperBound="-1"
          eType="#//ftg/Transformation" eOpposite="#//ftg/Transformation/input"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputOf" upperBound="-1"
          eType="#//ftg/Transformation" eOpposite="#//ftg/Transformation/output"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
          eType="#//pm/Object" eOpposite="#//pm/Object/typedBy"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transformation" eSuperTypes="#//base/Identifiable #//ftg/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
          eType="#//ftg/Formalism" eOpposite="#//ftg/Formalism/inputOf"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
          eType="#//ftg/Formalism" eOpposite="#//ftg/Formalism/outputOf"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
          eType="#//pm/Activity" eOpposite="#//pm/Activity/typedBy"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceConstraint" eType="#//resources/ResourceConstraint"
          eOpposite="#//resources/ResourceConstraint/transformation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//base/NamedElement"/>
  </eSubpackages>
  <eSubpackages name="pm" nsURI="metamodels.pm" nsPrefix="be.uantwerpen.msdl.metamodels">
    <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//base/Identifiable #//base/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1"
          eType="#//pm/Node" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="controlFlow" upperBound="-1"
          eType="#//pm/ControlFlow" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true" eSuperTypes="#//base/Identifiable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataFlowFrom" upperBound="-1"
          eType="#//pm/Node" eOpposite="#//pm/Node/dataFlowTo"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataFlowTo" upperBound="-1"
          eType="#//pm/Node" eOpposite="#//pm/Node/dataFlowFrom"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="controlIn" upperBound="-1"
          eType="#//pm/ControlFlow" eOpposite="#//pm/ControlFlow/to"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="controlOut" upperBound="-1"
          eType="#//pm/ControlFlow" eOpposite="#//pm/ControlFlow/from"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ControlFlow" eSuperTypes="#//base/Identifiable #//base/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1"
          eType="#//pm/Node" eOpposite="#//pm/Node/controlOut"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//pm/Node"
          eOpposite="#//pm/Node/controlIn"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true" eSuperTypes="#//pm/Node #//cost/CostItem #//pm/Typeable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typedBy" eType="#//ftg/Transformation"
          eOpposite="#//ftg/Transformation/types"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocation" upperBound="-1"
          eType="#//resources/Allocation" eOpposite="#//resources/Allocation/activity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="demand" upperBound="-1"
          eType="#//resources/Demand" eOpposite="#//resources/Demand/activity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="intent" upperBound="-1"
          eType="#//properties/Intent" eOpposite="#//properties/Intent/activity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ManualActivity" eSuperTypes="#//pm/Activity"/>
    <eClassifiers xsi:type="ecore:EClass" name="AutomatedActivity" eSuperTypes="#//pm/Activity"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundActivity" eSuperTypes="#//pm/Activity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" upperBound="-1"
          eType="#//pm/Activity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//pm/Node #//pm/Typeable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typedBy" eType="#//ftg/Formalism"
          eOpposite="#//ftg/Formalism/types"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Control" abstract="true" eSuperTypes="#//pm/Node"/>
    <eClassifiers xsi:type="ecore:EClass" name="Initial" eSuperTypes="#//pm/Control"/>
    <eClassifiers xsi:type="ecore:EClass" name="Final" abstract="true" eSuperTypes="#//pm/Control"/>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityFinal" eSuperTypes="#//pm/Final"/>
    <eClassifiers xsi:type="ecore:EClass" name="FlowFinal" eSuperTypes="#//pm/Final"/>
    <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="#//pm/Control"/>
    <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//pm/Control"/>
    <eClassifiers xsi:type="ecore:EClass" name="Merge" eSuperTypes="#//pm/Control"/>
    <eClassifiers xsi:type="ecore:EClass" name="Decision" eSuperTypes="#//pm/Control #//base/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Typeable" abstract="true" eSuperTypes="#//base/NamedElement"/>
  </eSubpackages>
  <eSubpackages name="properties" nsURI="metamodels.properties" nsPrefix="be.uantwerpen.msdl.metamodels">
    <eClassifiers xsi:type="ecore:EClass" name="PropertyModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
          eType="#//properties/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relationship" upperBound="-1"
          eType="#//properties/Relationship" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="intent" upperBound="-1"
          eType="#//properties/Intent" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//properties/IntentSubject #//base/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="relationshipLink" upperBound="-1"
          eType="#//properties/PropertyRelationshipLink" eOpposite="#//properties/PropertyRelationshipLink/property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Relationship" eSuperTypes="#//properties/IntentSubject #//base/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" lowerBound="1"
          eType="#//properties/Precision"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="propertyLink" upperBound="-1"
          eType="#//properties/PropertyRelationshipLink" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyRelationshipLink" eSuperTypes="#//base/Identifiable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
          eType="#//properties/RelationshipDirection"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
          eType="#//properties/Property" eOpposite="#//properties/Property/relationshipLink"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//properties/Relationship"/>
    <eClassifiers xsi:type="ecore:EEnum" name="Precision">
      <eLiterals name="L1" literal="L1"/>
      <eLiterals name="L2" value="1" literal="L2"/>
      <eLiterals name="L3" value="2" literal="L3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="RelationshipDirection">
      <eLiterals name="UNDIRECTED"/>
      <eLiterals name="PROPERTY" value="1"/>
      <eLiterals name="CONSTRAINT" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntentSubject" abstract="true" eSuperTypes="#//base/Identifiable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="intent" upperBound="-1"
          eType="#//properties/Intent" eOpposite="#//properties/Intent/subject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Intent" eSuperTypes="#//base/Identifiable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
          eType="#//pm/Activity" eOpposite="#//pm/Activity/intent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subject" lowerBound="1"
          eType="#//properties/IntentSubject" eOpposite="#//properties/IntentSubject/intent"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//properties/IntentType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="IntentType">
      <eLiterals name="UNKNOWN" literal="UNKNOWN"/>
      <eLiterals name="READ" value="1"/>
      <eLiterals name="MODIFY" value="2"/>
      <eLiterals name="CHECK" value="3"/>
      <eLiterals name="LOCK" value="4"/>
      <eLiterals name="RELEASE" value="5"/>
      <eLiterals name="CONTRACT" value="6"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="resources" nsURI="metamodels.resources" nsPrefix="be.uantwerpen.msdl.metamodels">
    <eClassifiers xsi:type="ecore:EClass" name="ResourceModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceType" upperBound="-1"
          eType="#//resources/ResourceType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" upperBound="-1"
          eType="#//resources/Resource" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocation" upperBound="-1"
          eType="#//resources/Allocation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="demand" upperBound="-1"
          eType="#//resources/Demand" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceConstraint" upperBound="-1"
          eType="#//resources/ResourceConstraint" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceType" eSuperTypes="#//base/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="specialize" eType="#//resources/ResourceType"
          eOpposite="#//resources/ResourceType/generalize"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="generalize" upperBound="-1"
          eType="#//resources/ResourceType" eOpposite="#//resources/ResourceType/specialize"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
          eType="#//resources/Resource" eOpposite="#//resources/Resource/typedBy"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocationConstraint"
          upperBound="-1" eType="#//resources/ResourceConstraint" eOpposite="#//resources/ResourceConstraint/resourceType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="demand" upperBound="-1"
          eType="#//resources/Demand" eOpposite="#//resources/Demand/resourceType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//base/NamedElement #//cost/CostItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typedBy" lowerBound="1"
          eType="#//resources/ResourceType" eOpposite="#//resources/ResourceType/types"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocation" upperBound="-1"
          eType="#//resources/Allocation" eOpposite="#//resources/Allocation/resource"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="availability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Allocation" eSuperTypes="#//base/Identifiable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
          eType="#//pm/Activity" eOpposite="#//pm/Activity/allocation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" lowerBound="1"
          eType="#//resources/Resource" eOpposite="#//resources/Resource/allocation"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Demand" eSuperTypes="#//base/Identifiable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceType" lowerBound="1"
          eType="#//resources/ResourceType" eOpposite="#//resources/ResourceType/demand"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
          eType="#//pm/Activity" eOpposite="#//pm/Activity/demand"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceConstraint" eSuperTypes="#//base/Identifiable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="transformation" lowerBound="1"
          eType="#//ftg/Transformation" eOpposite="#//ftg/Transformation/resourceConstraint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceType" lowerBound="1"
          eType="#//resources/ResourceType" eOpposite="#//resources/ResourceType/allocationConstraint"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="1"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="cost" nsURI="metamodels.cost" nsPrefix="be.uantwerpen.msdl.metamodels">
    <eClassifiers xsi:type="ecore:EClass" name="CostModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="costFactor" upperBound="-1"
          eType="#//cost/CostFactor" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CostFactor" eSuperTypes="#//base/NamedElement #//base/Identifiable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cost" upperBound="-1"
          eType="#//cost/Cost" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cost" eSuperTypes="#//base/Identifiable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="costItem" lowerBound="1"
          eType="#//cost/CostItem" eOpposite="#//cost/CostItem/cost"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CostItem" abstract="true" eSuperTypes="#//base/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cost" upperBound="-1"
          eType="#//cost/Cost" eOpposite="#//cost/Cost/costItem"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="base" nsURI="metamodels.base" nsPrefix="be.uantwerpen.msdl.metamodels">
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
