/*
 * generated by Xtext 2.9.1
 */
package be.uantwerpen.msdl.icm.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class IcmRuntimeModule extends AbstractIcmRuntimeModule {
}
