<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cost" nsURI="metamodels.cost" nsPrefix="be.uantwerpen.msdl.metamodels">
  <eClassifiers xsi:type="ecore:EClass" name="Cost" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="costOf" eType="ecore:EClass process.ecore#//Activity"
        eOpposite="process.ecore#//Activity/cost"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RatioScale" eSuperTypes="#//Cost">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ordinal" abstract="true" eSuperTypes="#//Cost"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expensive" eSuperTypes="#//Ordinal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cheap" eSuperTypes="#//Ordinal"/>
</ecore:EPackage>
