<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ftg" nsURI="metamodels.ftg" nsPrefix="be.uantwerpen.msdl.metamodels">
  <eClassifiers xsi:type="ecore:EClass" name="TransformationGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformation" upperBound="-1"
        eType="#//Transformation" containment="true" eOpposite="#//Transformation/transformationGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="language" upperBound="-1"
        eType="#//Language" containment="true" eOpposite="#//Language/transformationGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationGraph" lowerBound="1"
        eType="#//TransformationGraph" eOpposite="#//TransformationGraph/transformation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputLanguage" upperBound="-1"
        eType="#//Language" eOpposite="#//Language/inputOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputLanguage" upperBound="-1"
        eType="#//Language" eOpposite="#//Language/outputOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="ecore:EClass process.ecore#//Activity" eOpposite="process.ecore#//Activity/typedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Language">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputOf" upperBound="-1"
        eType="#//Transformation" eOpposite="#//Transformation/inputLanguage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputOf" upperBound="-1"
        eType="#//Transformation" eOpposite="#//Transformation/outputLanguage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationGraph" lowerBound="1"
        eType="#//TransformationGraph" eOpposite="#//TransformationGraph/language"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="ecore:EClass process.ecore#//Object" eOpposite="process.ecore#//Object/typedBy"/>
  </eClassifiers>
</ecore:EPackage>
