<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="process" nsURI="metamodels.process" nsPrefix="be.uantwerpen.msdl.metamodels">
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="#//Node"
        eOpposite="#//Node/process"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" lowerBound="1"
        eType="#//Process" eOpposite="#//Process/node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedNode" abstract="true" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true" eSuperTypes="#//NamedNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedBy" eType="ecore:EClass ftg.ecore#//Transformation"
        eOpposite="ftg.ecore#//Transformation/types"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cost" eType="ecore:EClass cost.ecore#//Cost"
        containment="true" eOpposite="cost.ecore#//Cost/costOf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManualActivity" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="AutomatedActivity" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//NamedNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedBy" lowerBound="1"
        eType="ecore:EClass ftg.ecore#//Language" eOpposite="ftg.ecore#//Language/types"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencyInputOf" upperBound="-1"
        eType="ecore:EClass dependency.ecore#//Dependency" eOpposite="dependency.ecore#//Dependency/input"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencyOutputOf" upperBound="-1"
        eType="ecore:EClass dependency.ecore#//Dependency" eOpposite="dependency.ecore#//Dependency/output"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="ecore:EClass property.ecore#//Property" eOpposite="property.ecore#//Property/derivedFrom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Control" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Initial" eSuperTypes="#//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="Final" abstract="true" eSuperTypes="#//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityFinal" eSuperTypes="#//Final"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowFinal" eSuperTypes="#//Final"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="#//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="Merge" eSuperTypes="#//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="Decision" eSuperTypes="#//Control"/>
</ecore:EPackage>
