<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="enactment" nsURI="metamodels.enactment" nsPrefix="org.proxima.metamodels">
  <eClassifiers xsi:type="ecore:EClass" name="Enactment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enactedProcessModel" lowerBound="1"
        eType="ecore:EClass processmodel.ecore#//ProcessModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="token" upperBound="-1"
        eType="#//Token" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentNode" eType="ecore:EClass processmodel.ecore#//pm/Node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" lowerBound="1" eType="#//ActivityState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subToken" upperBound="-1"
        eType="#//Token" eOpposite="#//Token/subTokenOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTokenOf" eType="#//Token"
        eOpposite="#//Token/subToken"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActivityState">
    <eLiterals name="READY"/>
    <eLiterals name="RUNNING" value="1"/>
    <eLiterals name="DONE" value="2"/>
  </eClassifiers>
</ecore:EPackage>
