/*
 * generated by Xtext 2.9.1
 */
package be.uantwerpen.msdl.icm.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class IcmUiModule extends AbstractIcmUiModule {
}
