/*
 * generated by Xtext 2.9.1
 */
package be.uantwerpen.msdl.icm.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IcmStandaloneSetup extends IcmStandaloneSetupGenerated {

	def static void doSetup() {
		new IcmStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
